### ISSUE TITLE
User assignment on new Task does not work

### ISSUE THREAD

**Issue by t6n** [mafigit/Komorebi#211]
If you create a new task und directly assign a user to this new task, the assignment has no effect.

**Comment by kmerz** [comment]
This needs work on the api.

I can only assign a user to a task of which I have an id. So the response of creating a model must contain the id of the new object.

**Comment by t6n** [comment]
Api change: https://github.com/mafigit/Komorebi/pull/230/commits/65a8d68070d7ec7d63bdd0b49d6d282161ee745c
